Title: ZSE Charts
Airports:
  Bravo:
    - SEA
  Charlie:
    - PDX
  Delta:
    - ALW
    - BFI
    - BLI
    - EUG
    - GEG
    - HIO
    - LMT
    - LWS
    - MFR
    - MWH
    - NUW
    - OLM
    - OTH
    - PAE
    - PDT
    - PSC
    - RDM
    - RNT
    - SFF
    - SLE
    - TCM
    - TIW
    - TTD
    - UAO
    - YKM
